config/routes.rb
Rails.application.routes.draw do
  # categories routes
  get "/categories" => "categories#index"

  post "/categories" => "categories#create"

  get "/categories/new" => "categories#new"

  get "/categories/:id/edit" => "categories#edit"

  get "/categories/:id" => "categories#show", as: "category"

  patch "/categories/:id" => "categories#update"

  delete "/categories/:id" => "categories#delete"

  # nested tasks routes
  get "/categories/:categories_id/tasks" => "tasks#index"

  get "/categories/:categories_id/tasks/:id" => "tasks#show", as: "task"

  get "/categories/:categories_id/tasks/:id/edit" => "tasks#edit", as: "task_edit"

  patch "/categories/:categories_id/tasks/:id" => "tasks#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :bigint           not null, primary key
#  description :string
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Category < ApplicationRecord
  validates(:name, presence: true)
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  description :string
#  due_date    :datetime
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint
#
# Indexes
#
#  index_tasks_on_category_id  (category_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#
class Task < ApplicationRecord
  belongs_to :category
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    render :new
  end

  def show
    @category = Category.find(params[:id])
    render :show
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url, notice: "Category was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def delete
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_url
  end

  def edit
    render :edit
  end

  def update
    @category = Category.find(params[:id]).tasks

    if @category.update(category_params)
      redirect_to category_url(category_params), notice: "Category was successfully updated."
    else
      render :edit, status: unprocessable_entity
    end
  end



  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @category = Category.find(params[:categories_id])
  end

  def show
    @task = Category.find(params[:categories_id]).tasks.find(params[:id])
  end

  def edit
    @task = Category.find(params[:categories_id]).tasks.find(params[:id])
  end

  def update
    #@task = Category.find(params[:categories_id]).tasks.find(params[:id])
    #puts ">>>>>>>>>>> #{@task} #{@task.update(params[:name, :description])}"
    @task = Task.find(params[:id])
    p ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> "
    p @task
    p ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> "
    if @task.update(task_params)
      p ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> "
      p "  Update success"
      p ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> "
      redirect_to task_url(@task.category_id, @task.id)
    else
      p ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> "
      p "  Update failed"
      p ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> "
      render :edit, status: unprocessable_entity
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<h1>Update Category</h1>

<%= form_with(model: @category) do |form| %>
  <div><%= form.text_field :name %></div>
  <div><%= form.text_field :description %></div>
  <%= form.submit %>
<% end %>

app/views/categories/index.html.erb
<div id="categories">
  <% @categories.each do |category| %>
    <p><%= category.name %> </p>
    <p><%= category.description %> </p>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1>Create Category</h1>
<%= form_with(model: @category, url: categories_url, method: :post, local: true) do |f| %>
  <div>
    <%= f.label :name, "custom category name" %>
    <%= f.text_field :name  %>
  </div>


  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <%= f.submit %>
<% end %>

app/views/categories/show.html.erb
<% @category.attributes.each do |a| %>
  <%= a %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsJournalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= form_with(model: [@task], local: true) do |form| %>
  <%= @task.category_id %>
  <br/><br/>
  <div>Task name: <%= form.text_field :name %></div>
  <div>Task description: <%= form.text_field :description %></div>
  <%= form.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1> Category Tasks View </h1>
<div>
  Category Name: <%= @category.name %>
</div>

<div>
  Tasks: <br />
  <% @category.tasks.each do |task| %>
    <p><%= link_to "Edit", task_edit_url(task.category_id, task.id) %>

    Task Name: <%= task.name %> -- Task description: <%= task.description %></p>
    <br/>
  <% end %>
</div>

<h2> This should be the end </h2>

app/views/tasks/show.html.erb
<h1>Displaying specific task</h1>
<h2>Task Name: <%= @task.name %></h2>
<h2>Task Description: <%= @task.description %></h2>